spring:
  application:
    name: app-gestion-de-cursos

datasource:
  url: jdbc:postgresql://localhost:5435/gestion_cursos
  username: username
  password: 1234
  driver-class-name: org.postgresql.Driver

  jpa:
    ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true